### ISSUE TITLE
GET /api/wav2lip/play/default/silence HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by gurilagardnr** [Mozer/wav2lip_extension#4]
GET /api/wav2lip/play/default/silence HTTP/1.1" 404 -

Using xtts with xtts_api_server --deepspeed --listen --lowvram  --output c:\\SillyTavern-extras\\ and extras default whisper implementation.  using default provided video file.   wav2lip module appears to initialize upon extras server start, but once a message gets sent to wav2lip the above error is posted to console.  Can you provide any clues as to where to look to resolve this?

**Comment by Mozer** [comment]
There are two modes for this extension: 'video message', and 'live stream' (you can switch them in extension settings).  silence.mp4 is meant for a live stream mode. It is supposed to be played in a loop after the character is finished speaking, mimicking a live video stream (like twitch). silence.mp4 should be made by you for your character manually, it's basically any video where the character is not speaking, longer videos are better looking. 

For a test you can just copy \SillyTavern-Extras\modules\wav2lip\input\default\emma.mp4 and rename it to silence.mp4 to test it. I added this info to readme.

**Comment by Mozer** [comment]
At first I was trying to make emma.mp4 silent by removing emma's lips movement by making her say '..................' using silero. But it looked creepy, so I removed the file.

**Comment by Mozer** [comment]
I added silence.mp4 (2 second video of silent emma) to https://github.com/Mozer/wav2lip/
File should be in \SillyTavern-Extras\modules\wav2lip\input\default\
I also excluded silence.mp4 from the list of random files to use when generating a video message.
